---
title: 'Assessing User Satisfaction: A Comparative Study on Android and iOS Platforms'
author: 
"Edora Frances Anne V. Arcenas  
Karen Castigador
Jessa Octavio"
date: "2024-04-25"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
Title:
  Assessing User Satisfaction: A Comparative Study on Android and iOS Platforms
Members:
  Edora Frances Anne V. Arcenas  
  Karen Castigador
  Jessa Octavio

Performance Expectancy

1. How often do you experience delays or lags while using the [Android/iOS] platform?

2. On a scale of 1-5, how well does your Android/iOS device meet your performance expectations?

3. How crucial is the performance of your Android/iOS device in helping you accomplish your goals?

Effort Expectancy

1. To what extent do you believe that using the [Android/iOS] platform improves your productivity and efficiency?

2. How easy do you find it to learn and use your Android/iOS device?

3. How would you rate the overall performance of the [Android/iOS] platform in meeting your expectations?

4. On a scale of 1-5, how simple is it for you to perform tasks on your Android/iOS device?

Attitude Toward Using Technology

1. On a scale of 1-5, How much do you enjoy using your Android/iOS device?

2. Do you think using an Android/iOS device has a significant impact on your daily life?

3. How important is it for you to stay updated with the latest technology, such as Android and iOS devices?

4. On a scale of 1-5, how positive is your attitude toward using your Android/iOS device?

Social Influence

1. How much do your friends and family influence your decision to use an Android/iOS device?

2. How important are the opinions of others in your decision to use an Android/iOS device?

3. How much do you think the popularity of Android and iOS devices among your social circle affects your own choice?

Facilitating Conditions

1. How satisfied are you with the support and resources available for your Android/iOS device?

2. To what extent do you find it convenient to access apps and services on your Android/iOS device?

3. How easy is it for you to get help or troubleshoot issues with your Android/iOS device?

4. How much do you think the availability of apps and services on your Android/iOS device influences your satisfaction?

Self-Efficacy

1. How comfortable are you with learning new features and functions on your Android/iOS device?

2. Do you believe you can troubleshoot common issues with your Android/iOS device on your own?

3. How much do you think your skills in using technology contribute to your satisfaction with your Android/iOS device?

4. Compared to other users, do you think you are more capable of handling your Android/iOS device?

Anxiety

1. How worried are you about making mistakes while using your Android/iOS device?

2. To what extent do you feel stressed when using your Android/iOS device?

3. How much do you think the fear of damaging your Android/iOS device affects your satisfaction?

4. Compared to other users, do you think you experience more or less anxiety when using your Android/iOS device?

Behavioral Intention to Use the System:

1. How likely are you to continue using your Android/iOS device in the future?

2. How important is it for you to have an Android/iOS device in your daily life?

3. How much do you think your current satisfaction with your Android/iOS device influences your intention to continue using it?

4. Compared to when you first started using your Android/iOS device, how much has your intention to use it increased or decreased?
```